tap "koekeishiya/formulae"
tap "FelixKratz/formulae"

brew "rg"
brew "htop"
brew "tig"
brew "antigen"
brew "gnupg"
brew "fd"
brew "fzf"
brew "neovim"
brew "koekeishiya/formulae/yabai"
brew "koekeishiya/formulae/skhd"
brew "FelixKratz/formulae/sketchybar"
brew "starship"
brew "jq"
brew "shellcheck"
brew "shfmt"
brew "stylua"
brew "git-lfs"

cask "kitty"
cask "font-jetbrains-mono-nerd-font"
cask "karabiner-elements"
cask "raycast"

