# Starship prompt - Catppuccin Macchiato
add_newline = true
command_timeout = 1200

format = "$username$hostname$directory$git_branch$git_status$nodejs$rust$python$aws$golang$kotlin$time$line_break$character"

[palettes.catppuccin]
rosewater = "#f5e0dc"
flamingo  = "#f2cdcd"
pink      = "#f5c2e7"
mauve     = "#cba6f7"
red       = "#f38ba8"
maroon    = "#eba0ac"
peach     = "#fab387"
yellow    = "#f9e2af"
green     = "#a6e3a1"
teal      = "#94e2d5"
sky       = "#89dceb"
sapphire  = "#74c7ec"
blue      = "#89b4fa"
lavender  = "#b4befe"
text      = "#cdd6f4"
subtext1  = "#bac2de"
subtext0  = "#a6adc8"
overlay2  = "#9399b2"
overlay1  = "#7f849c"
overlay0  = "#6c7086"
surface2  = "#585b70"
surface1  = "#45475a"
surface0  = "#313244"
base      = "#1e1e2e"
mantle    = "#181825"
crust     = "#11111b"

[character]
success_symbol = "[❯](bold blue)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold mauve)"

[directory]
truncation_length = 3
style = "bold lavender"

[git_branch]
symbol = " "
style = "bold teal"

[git_status]
style = "yellow"

[time]
disabled = false
format = "[$time]($style) "
time_format = "%R"
style = "subtext1"


